type vendor {
    name : String! @unique ,
    address : String! ,
    contactNumber : String!,
    PAN : String!,
    email : String!,
    vendorContact : {
        firstName : String!,
        lastName : String!,
        contactNumber : String!,
        email : String!
    },
    keyUUID : String! @unique 
}